title: KVP
description: A starter template for a Jeykll site using the Just the Docs theme!
# theme: just-the-docs
# remote_theme: just-the-docs/just-the-docs
remote_theme: pmarsceill/just-the-docs

plugins:
  - jekyll-default-layout

url: https://selvi-rminds.github.io

# aux_links:
 # Template Repository: https://github.com/just-the-docs/just-the-docs-template
